=== nik7007/AssignmentDP2/wsdl/WFInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"> <!--attributeFormDefault="unqualified" elementFormDefault="qualified" -->

    <xs:element name="root" type="rootType">

        <xs:keyref name="actionStatus_RefID" refer="action_ID">
            <xs:selector xpath="action_statusType"/>
            <xs:field xpath="@name"/>
        </xs:keyref>

    </xs:element>

    <xs:complexType name="action_statusType">
        <xs:sequence>
            <xs:element type="actorType" name="actor" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:dateTime" name="date" use="optional"/>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:boolean" name="taken_in_charge" use="optional" default="false"/>
        <xs:attribute type="xs:boolean" name="terminated" use="optional" default="false"/>
    </xs:complexType>

    <xs:complexType name="actorType">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="role" use="required"/>
    </xs:complexType>

    <xs:complexType name="rootType">
        <xs:sequence>
            <xs:element type="workflowType" name="workflow" minOccurs="0" maxOccurs="unbounded">

                <xs:key name="action_ID">
                    <xs:selector xpath="simple_actionType|process_actionType"/>
                    <xs:field xpath="@name"/>
                </xs:key>

                <xs:keyref name="action_RefID" refer="action_ID">
                    <xs:selector xpath="sub_actionType"/>
                    <xs:field xpath="@name_ref"/>
                </xs:keyref>

            </xs:element>

            <xs:element type="processType" name="process" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="workflowType">
        <xs:sequence maxOccurs="unbounded" minOccurs="1">
            <xs:choice>
                <xs:element type="simple_actionType" name="simple_action" minOccurs="0"/>
                <xs:element type="process_actionType" name="process_action" minOccurs="0"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute type="xs:ID" name="name"/>
    </xs:complexType>


    <xs:complexType name="processType">
        <xs:sequence>
            <xs:element type="action_statusType" name="action_status" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:dateTime" name="date" use="required"/>
        <xs:attribute type="xs:IDREF" name="workflow" use="required"/>
    </xs:complexType>

    <xs:complexType name="actionType">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="role" use="required"/>
        <xs:attribute type="xs:boolean" name="auto" use="optional" default="false"/>
    </xs:complexType>


    <xs:complexType name="sub_actionType">
        <xs:attribute type="xs:string" name="name_ref" use="optional"/>
    </xs:complexType>

    <xs:complexType name="simple_actionType">
        <xs:complexContent>
            <xs:extension base="actionType">
                <xs:sequence>
                    <xs:element type="sub_actionType" name="sub_action" maxOccurs="unbounded" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="process_actionType">
        <xs:complexContent>
            <xs:extension base="actionType">
                <xs:attribute type="xs:IDREF" name="sub_workflow" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== nik7007/AssignmentDP2/xsd/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="WFInfo.xsd">
    <workflow name="ArticleProduction">
        <simple_action auto="false" name="Publication" role="Editor"/>
        <simple_action auto="true" name="Writing" role="Journalist">
            <sub_action name_ref="Checking"/>
        </simple_action>
        <simple_action auto="false" name="Revising" role="Journalist">
            <sub_action name_ref="Checking"/>
        </simple_action>
        <simple_action auto="false" name="Checking" role="Editor">
            <sub_action name_ref="Revising"/>
            <sub_action name_ref="Publication"/>
        </simple_action>
    </workflow>
    <process date="2015-10-15T00:16:40.000+02:00" workflow="ArticleProduction">
        <action_status date="2015-10-15T09:12:40.000" name="Writing" taken_in_charge="true" terminated="true">
            <actor name="Eva Bianchi" role="Journalist"/>
        </action_status>
        <action_status date="2015-10-17T04:53:40.000" name="Checking" taken_in_charge="true" terminated="true">
            <actor name="Joseph Green" role="Editor"/>
        </action_status>
        <action_status date="2015-10-18T03:09:40.000" name="Revising" taken_in_charge="true" terminated="true">
            <actor name="Beppe Baresi" role="Journalist"/>
        </action_status>
        <action_status name="Checking" taken_in_charge="false" terminated="false"/>
    </process>
    <process date="2015-10-09T21:03:40.000" workflow="ArticleProduction">
        <action_status date="2015-10-10T19:35:40.000" name="Writing" taken_in_charge="true" terminated="true">
            <actor name="Eva Bianchi" role="Journalist"/>
        </action_status>
        <action_status name="Checking" taken_in_charge="true" terminated="false">
            <actor name="Anna White" role="Editor"/>
        </action_status>
    </process>
    <process date="2015-10-16T10:20:40.000" workflow="ArticleProduction">
        <action_status date="2015-10-17T10:24:40.000" name="Writing" taken_in_charge="true" terminated="true">
            <actor name="Eva Bianchi" role="Journalist"/>
        </action_status>
        <action_status date="2015-10-17T10:26:40.000" name="Checking" taken_in_charge="true" terminated="true">
            <actor name="Anna White" role="Editor"/>
        </action_status>
        <action_status date="2015-10-18T09:33:40.000" name="Revising" taken_in_charge="true" terminated="true">
            <actor name="Eva Bianchi" role="Journalist"/>
        </action_status>
        <action_status date="2015-10-20T05:40:40.000" name="Checking" taken_in_charge="true" terminated="true">
            <actor name="Anna White" role="Editor"/>
        </action_status>
        <action_status name="Publication" taken_in_charge="false" terminated="false"/>
    </process>
    <process date="2015-10-13T08:42:40.000" workflow="ArticleProduction">
        <action_status date="2015-10-14T11:46:40.000" name="Writing" taken_in_charge="true" terminated="true">
            <actor name="Beppe Baresi" role="Journalist"/>
        </action_status>
        <action_status date="2015-10-16T10:16:40.000" name="Checking" taken_in_charge="true" terminated="true">
            <actor name="Henry H Francese" role="Editor"/>
        </action_status>
        <action_status name="Publication" taken_in_charge="false" terminated="false"/>
    </process>
    <process date="2015-10-21T11:28:40.000" workflow="ArticleProduction">
        <action_status name="Writing" taken_in_charge="false" terminated="false"/>
    </process>
    <process date="2015-10-12T16:30:40.000" workflow="ArticleProduction">
        <action_status date="2015-10-12T20:19:40.000" name="Writing" taken_in_charge="true" terminated="true">
            <actor name="Eva Bianchi" role="Journalist"/>
        </action_status>
        <action_status date="2015-10-13T19:05:40.000" name="Checking" taken_in_charge="true" terminated="true">
            <actor name="Anna White" role="Editor"/>
        </action_status>
        <action_status date="2015-10-15T11:31:40.000" name="Revising" taken_in_charge="true" terminated="true">
            <actor name="Beppe Baresi" role="Journalist"/>
        </action_status>
        <action_status date="2015-10-15T23:53:40.000" name="Checking" taken_in_charge="true" terminated="true">
            <actor name="Joseph Green" role="Editor"/>
        </action_status>
        <action_status name="Revising" taken_in_charge="false" terminated="false"/>
    </process>
    <process date="2015-10-09T03:29:40.000" workflow="ArticleProduction">
        <action_status date="2015-10-10T21:35:40.000" name="Writing" taken_in_charge="true" terminated="true">
            <actor name="Eva Bianchi" role="Journalist"/>
        </action_status>
        <action_status date="2015-10-12T05:29:40.000" name="Checking" taken_in_charge="true" terminated="true">
            <actor name="Anna White" role="Editor"/>
        </action_status>
        <action_status date="2015-10-12T09:50:40.000" name="Publication" taken_in_charge="true" terminated="true">
            <actor name="Joseph Green" role="Editor"/>
        </action_status>
    </process>
    <process date="2015-10-19T20:52:40.000" workflow="ArticleProduction">
        <action_status name="Writing" taken_in_charge="false" terminated="false"/>
    </process>
</root>
